
framework:
    secret: '%env(APP_SECRET)%'

    session:
        # Handler par défaut (file/session ou autre selon vos besoins)
        # handler_id: session.handler.native_file

        # Sécurisation du cookie de session
        enabled: true
        cookie_secure: auto     # → true en HTTPS
        cookie_httponly: true   # → interdit l’accès par JS
        cookie_samesite: strict # → anti‐CSRF

    csrf_protection: true

    cache:
        pools:
            my_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # Optional, set cache lifetime

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
