# config/packages/messenger.yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            failed:
                dsn: 'doctrine://default?queue_name=failed'

            sync:
                dsn: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Envoi direct (synchrone) des e-mails
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync

            # Les notifications Chat et SMS restent asynchrones
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage:   async
