# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin:   ['http://127.0.0.1:8000']  # Votre front local :contentReference[oaicite:0]{index=0}
        allow_methods:  ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers:  ['Content-Type', 'X-Requested-With']
        expose_headers: []
        max_age:        3600
        allow_credentials: true               # Active l’envoi de cookies (HttpOnly, etc.) :contentReference[oaicite:1]{index=1}
    paths:
        '^/api/':
            # Hérite de allow_methods, allow_headers, etc.
            allow_origin:     ['http://127.0.0.1:8000']  # Doit être répété ici :contentReference[oaicite:2]{index=2}
            allow_credentials: true
